## Illustrates `numpy` vs `einsum`
In deep learning, we perform a lot of tensor operations. `einsum` simplifies and unifies the APIs for these operations.

`einsum` can be found in numerical computation libraries and deep learning frameworks.
Let us demonstrate how to import and use `einsum` in `numpy`, TensorFlow and PyTorch. 

In [1]:
import numpy as np
#from torch import einsum
import torch
from numpy import einsum

In [2]:
w = np.arange(6).reshape(2,3).astype(np.float32)
x = np.ones((3,1), dtype=np.float32)

print("w:\n", w)
print("x:\n", x)

y = np.matmul(w, x)
print("y:\n", y)

#y = einsum('ij,jk->ik', torch.from_numpy(w), torch.from_numpy(x))
y = einsum('ij,jk->ik', w, x)
print("y:\n", y)


w:
 [[0. 1. 2.]
 [3. 4. 5.]]
x:
 [[1.]
 [1.]
 [1.]]
y:
 [[ 3.]
 [12.]]
y:
 [[ 3.]
 [12.]]


### Tensor multiplication with transpose in `numpy` and `einsum`

In [3]:
w = np.arange(6).reshape(2,3).astype(np.float32)
x = np.ones((1,3), dtype=np.float32)

print("w:\n", w)
print("x:\n", x)

y = np.matmul(w, np.transpose(x))
print("y:\n", y)

y = einsum('ij,kj->ik', w, x)
print("y:\n", y)

w:
 [[0. 1. 2.]
 [3. 4. 5.]]
x:
 [[1. 1. 1.]]
y:
 [[ 3.]
 [12.]]
y:
 [[ 3.]
 [12.]]


### Properties of square matrices in `numpy` and `einsum`

We demonstrate diagonal.

In [4]:
w = np.arange(9).reshape(3,3).astype(np.float32)
d = np.diag(w)
print("w:\n", w)
print("d:\n", d)
d = einsum('ii->i', w)
print("d:\n", d)

w:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
d:
 [0. 4. 8.]
d:
 [0. 4. 8.]


Trace.

In [5]:
t = np.trace(w)
print("t:\n", t)

t = einsum('ii->', w)
print("t:\n", t)

t:
 12.0
t:
 12.0


Sum along an axis.

In [6]:
s = np.sum(w, axis=0)
print("s:\n", s)

s = einsum('ij->j', w)
print("s:\n", s)

s:
 [ 9. 12. 15.]
s:
 [ 9. 12. 15.]


Let us demonstrate tensor transpose. We can also use `w.T` to transpose `w` in numpy.

In [7]:
t = np.transpose(w)
print("t:\n", t)

t = einsum("ij->ji", w)
print("t:\n", t)

t:
 [[0. 3. 6.]
 [1. 4. 7.]
 [2. 5. 8.]]
t:
 [[0. 3. 6.]
 [1. 4. 7.]
 [2. 5. 8.]]


### Dot, inner and outer products in `numpy` and `einsum`.

In [8]:
a = np.ones((3,), dtype=np.float32)
b = np.ones((3,), dtype=np.float32) * 2

print("a:\n", a)
print("b:\n", b)

d = np.dot(a,b)
print("d:\n", d)
d = einsum("i,i->", a, b)
print("d:\n", d)

i = np.inner(a, b)
print("i:\n", i)
i = einsum("i,i->", a, b)
print("i:\n", i)

o = np.outer(a,b)
print("o:\n", o)
o = einsum("i,j->ij", a, b)
print("o:\n", o)


a:
 [1. 1. 1.]
b:
 [2. 2. 2.]
d:
 6.0
d:
 6.0
i:
 6.0
i:
 6.0
o:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
o:
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
