In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# numpy package
import numpy as np

# keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import plot_model

# generate x data
x = np.arange(-1,1,0.2)
x = np.reshape(x, [-1,1])

# generate y data
y = 2 * x + 3

# True if noise is added to y
is_noisy = True

# add noise if enabled
if is_noisy:
    noise = np.random.uniform(-0.1, 0.1, x.shape)
    x = x + noise

# deep learning method
# build 2-layer MLP network 
model = Sequential()
# 1st MLP has 8 units (perceptron), input is 1-dim
model.add(Dense(units=8, input_dim=1))
# 2nd MLP has 1 unit, output is 1-dim
model.add(Dense(units=1))
# print summary to double check the network
model.summary()
# create a nice image of the network model
plot_model(model, to_file='linear-model.png', show_shapes=True)
# indicate the loss function and use stochastic gradient descent
# (sgd) as optimizer
model.compile(loss='mse', optimizer='sgd')
# feed the network with complete dataset (1 epoch) 100 times
# batch size of sgd is 4
model.fit(x, y, epochs=100, batch_size=4)
# simple validation by predicting the output based on x
ypred = model.predict(x)

# linear algebra method
ones = np.ones(x.shape)
# A is the concat of x and 1s
A = np.concatenate([x,ones], axis=1)
# compute k using using pseudo-inverse
k = np.matmul(np.linalg.pinv(A), y) 
print("k (Linear Algebra Method):")
print(k)
# predict the output using linear algebra solution
yla = np.matmul(A, k)

# print ground truth, linear algebra, MLP solutions
outputs = np.concatenate([y, yla, ypred], axis=1)
print("Ground Truth, Linear Alg Prediction, MLP Prediction")
print(outputs)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 8)                 16        
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 9         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
10/10 [==============================] - 0s 10ms/step - loss: 8.8176
Epoch 2/100
10/10 [==============================] - 0s 376us/step - loss: 7.5185
Epoch 3/100
10/10 [==============================] - 0s 515us/step - loss: 6.4733
Epoch 4/100
10/10 [==============================] - 0s 560us/step - loss: 5.5393
Epoch 5/100
10/10 [==============================] - 0s 565us/step - loss: 4.7070
Epoch 6/100
10/10 [==============================] - 0s 406us/step - loss: 3.9639
Epoch 7/100
10/10 [==============================] 

10/10 [==============================] - 0s 377us/step - loss: 0.0056
Epoch 93/100
10/10 [==============================] - 0s 585us/step - loss: 0.0059
Epoch 94/100
10/10 [==============================] - 0s 629us/step - loss: 0.0056
Epoch 95/100
10/10 [==============================] - 0s 713us/step - loss: 0.0055
Epoch 96/100
10/10 [==============================] - 0s 442us/step - loss: 0.0057
Epoch 97/100
10/10 [==============================] - 0s 410us/step - loss: 0.0056
Epoch 98/100
10/10 [==============================] - 0s 495us/step - loss: 0.0059
Epoch 99/100
10/10 [==============================] - 0s 476us/step - loss: 0.0057
Epoch 100/100
10/10 [==============================] - 0s 447us/step - loss: 0.0057
k (Linear Algebra Method):
[[1.93661485]
 [2.97435214]]
Ground Truth, Linear Alg Prediction, MLP Prediction
[[1.         1.07363151 1.07403767]
 [1.4        1.44517422 1.4450146 ]
 [1.8        1.79244333 1.79175496]
 [2.2        2.16856718 2.16730618]
 [2.6        