## Simple linear regression
Solution using MLP and Linear Algebra

In [6]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# numpy package
import numpy as np

# keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import plot_model

# generate x data
x = np.arange(-1,1,0.2)
x = np.reshape(x, [-1,1])

# generate y data
y = 2 * x + 3

# True if noise is added to y
is_noisy = True

# add noise if enabled
if is_noisy:
    noise = np.random.uniform(-0.1, 0.1, x.shape)
    x = x + noise

# deep learning method
# build 2-layer MLP network 
model = Sequential()
# 1st MLP has 8 units (perceptron), input is 1-dim
model.add(Dense(units=8, input_dim=1))
# 2nd MLP has 1 unit, output is 1-dim
model.add(Dense(units=1))
# print summary to double check the network
model.summary()
# create a nice image of the network model
plot_model(model, to_file='linear-model.png', show_shapes=True)
# indicate the loss function and use stochastic gradient descent
# (sgd) as optimizer
model.compile(loss='mse', optimizer='sgd')
# feed the network with complete dataset (1 epoch) 100 times
# batch size of sgd is 4
model.fit(x, y, epochs=100, batch_size=4)
# simple validation by predicting the output based on x
ypred = model.predict(x)

# linear algebra method
ones = np.ones(x.shape)
# A is the concat of x and 1s
A = np.concatenate([x,ones], axis=1)
# compute k using using pseudo-inverse
k = np.matmul(np.linalg.pinv(A), y) 
print("k (Linear Algebra Method):")
print(k)
# predict the output using linear algebra solution
yla = np.matmul(A, k)

# print ground truth, linear algebra, MLP solutions
outputs = np.concatenate([y, yla, ypred], axis=1)
print("Ground Truth, Linear Alg Prediction, MLP Prediction")
print(outputs)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 8)                 16        
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 9         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
10/10 [==============================] - 0s 16ms/step - loss: 8.5952
Epoch 2/100
10/10 [==============================] - 0s 467us/step - loss: 6.6294
Epoch 3/100
10/10 [==============================] - 0s 480us/step - loss: 5.0443
Epoch 4/100
10/10 [==============================] - 0s 507us/step - loss: 3.6412
Epoch 5/100
10/10 [==============================] - 0s 611us/step - loss: 2.6522
Epoch 6/100
10/10 [==============================] - 0s 484us/step - loss: 2.0336
Epoch 7/100
10/10 [==============================] 

10/10 [==============================] - 0s 756us/step - loss: 0.0076
Epoch 93/100
10/10 [==============================] - 0s 747us/step - loss: 0.0076
Epoch 94/100
10/10 [==============================] - 0s 534us/step - loss: 0.0076
Epoch 95/100
10/10 [==============================] - 0s 512us/step - loss: 0.0076
Epoch 96/100
10/10 [==============================] - 0s 418us/step - loss: 0.0076
Epoch 97/100
10/10 [==============================] - 0s 370us/step - loss: 0.0077
Epoch 98/100
10/10 [==============================] - 0s 473us/step - loss: 0.0076
Epoch 99/100
10/10 [==============================] - 0s 686us/step - loss: 0.0077
Epoch 100/100
10/10 [==============================] - 0s 567us/step - loss: 0.0077
k (Linear Algebra Method):
[[1.96483218]
 [2.98636007]]
Ground Truth, Linear Alg Prediction, MLP Prediction
[[1.         1.05636319 1.06256056]
 [1.4        1.40266383 1.40783095]
 [1.8        1.78023204 1.78427577]
 [2.2        2.02006013 2.02339053]
 [2.6        